[project]
name = 'Decentralized-Sustainable-Sourcing-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.audit-scheduling]
path = 'contracts/audit-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.certification]
path = 'contracts/certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.standards-compliance]
path = 'contracts/standards-compliance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
